services:
  kochbuchdb:
    image: postgres
    environment:
      - POSTGRES_USER=kochbuch
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kochbuchdb
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 7070:8080